SUSE/azurectl

Makefile, azure_cli/account.py, azure_cli/app.py, azure_cli/azure_cli.py, azure_cli/cli.py, azure_cli/container.py, azure_cli/data_collector.py, azure_cli/disk.py, azure_cli/exceptions.py, azure_cli/help.py, azure_cli/logger.py, azure_cli/storage_account.py, bin/azure-cli, doc/README.md, setup.cfg, setup.py, test/data/config, test/unit/cli_test.py, test/unit/container_test.py, test/unit/data_collector_test.py, test/unit/disk_test.py, test/unit/help_test.py, test/unit/logger_test.py, test/unit/storage_account_test.py
Start with a proposal for the azure-cli project including
tests based on nose, commandline parsing based on docopt
and an initial structure for implementing commands
=> Initial azure commandline tool interface

azure_cli/app.py, azure_cli/cli.py, azure_cli/exceptions.py, azure_cli/image.py, azure_cli/service_account.py, test/data/config, test/unit/image_test.py, test/unit/service_account_test.py, tools/service.sh
implemented service account handling and the list
command which prints the available os images for
the configured subscription
=> Added image command

README.md
These are some suggestions for changes plus typo corrections.
=> Proofread and correct README.md for azure-cli

azure_cli/compute_storage_task.py, test/unit/compute_storage_task_test.py
In addition document the available option values
=> Added --quiet option for upload

azure_cli/azurectl_exceptions.py, azure_cli/compute_image_task.py, azure_cli/image.py, doc/man/azurectl::compute::image.md, test/unit/image_test.py
This command implements the creation of an Os image
from a VHD disk image file stored in a Microsoft Azure
storage container
=> Added azurectl compute image create command

README.md, azure_cli/azurectl.py, azure_cli/compute_image_task.py, azure_cli/compute_storage_task.py, azure_cli/container.py, azure_cli/help.py, azure_cli/image.py, azure_cli/logger.py, azure_cli/storage.py, test/unit/azure_account_test.py, test/unit/cli_test.py, test/unit/compute_image_task_test.py, test/unit/compute_storage_task_test.py, test/unit/config_test.py, test/unit/container_test.py, test/unit/data_collector_test.py, test/unit/help_test.py, test/unit/image_test.py, test/unit/logger_test.py, test/unit/nose_helper.py, test/unit/storage_test.py, test/unit/xz_test.py
The python logging class offers most of the functionality
we need to log our messages. However it does not provide
a progress indicator. Thus the logging class as it is used
here is also extended by a progress indicator
=> Use python logging class

azure_cli/cli.py, azure_cli/compute_image_task.py, azure_cli/compute_storage_task.py, azure_cli/data_collector.py, azure_cli/data_output.py, doc/man/azurectl.md, doc/man/azurectl::compute::storage::container.md, test/unit/cli_test.py, test/unit/compute_image_task_test.py, test/unit/compute_storage_task_test.py, test/unit/data_collector_test.py, test/unit/data_output_test.py, tools/completion_generator
In order to support different output styles e.g json, XML or machine
readable a new class to encapsulate this has been introduced. By
default we will use json as output format. Along with this change
also colored output is added which Fixes #11
=> Added DataOutput class

README.md
Please review the following changes:
* b17be75 Update README
* bdda36a Added information about azurectl setup account use
=> [Review] Request from 'schaefi' @ 'SUSE/azurectl/review_150608_doc_update_azurectl_config'

.travis.script, .travis.yml, azurectl/azurectl_exceptions.py, azurectl/compute_storage_task.py, azurectl/fileshare.py, doc/man/azurectl::compute::storage::share.md, test/unit/cli_test.py, test/unit/compute_storage_task_test.py, test/unit/fileshare_test.py
azurectl compute storage share list, create and delete will be
added with this commit. Once created a file share can be mounted
using a CIFS mount
=> Added support for the Azure File Share service

azurectl/azure_account.py, azurectl/compute_vm_task.py, doc/man/azurectl::compute::vm.md, test/unit/azure_account_test.py, test/unit/compute_vm_task_test.py
List available instance types and their attributes
=> Added support for compute vm types

README.md
Could be helpful to see buid status of Travis CI
=> Added Travis batch image

setup.py
See https://build.opensuse.org/package/revisions/devel:languages:python/python-azure-sdk
=> Increment azure-sdk dependency to match version in OBS.

.travis.script, azurectl/azurectl_exceptions.py, azurectl/compute_image_task.py, azurectl/image.py, doc/man/azurectl::compute::image.md, test/unit/compute_image_task_test.py, test/unit/image_test.py
Added support for VM image replication and unreplication based on a patch I made for the Azure service management (legacy) SDK
=> Compute image replicate

azurectl/azurectl_exceptions.py, azurectl/compute_image_task.py, azurectl/image.py, doc/man/azurectl::compute::image.md, test/unit/compute_image_task_test.py, test/unit/image_test.py
Added support for publishing previously replicated images
=> Support for VM publishing

azurectl/azure_account.py, azurectl/compute_image_task.py, azurectl/compute_request_task.py, azurectl/compute_storage_task.py, azurectl/compute_vm_task.py, azurectl/setup_account_task.py, azurectl/version.py, doc/man/azurectl::compute::request.md, test/unit/azure_account_test.py, test/unit/compute_request_task_test.py, tools/coverage-check
Added support for obtaining request status and also waiting
for request completion for service management tasks
=> Added request management

azurectl/image.py, test/unit/image_test.py
azurectl compute image list did not show all information
=> show all image attributes

azurectl/compute_vm_task.py, azurectl/virtual_machine.py, test/unit/compute_vm_task_test.py, test/unit/virtual_machine_test.py
Resolves https://github.com/SUSE/azurectl/issues/62 .
=> Don't provide the media_link attribute when creating a VM

Makefile, package/spec-template, setup.py
Instead of requiring an exact version we opened this to
match the major version and its releases. This fixes Issue #73
=> Update module dependencies strictness

.travis.script, azurectl/azurectl_exceptions.py, azurectl/compute_image_task.py, azurectl/defaults.py, azurectl/image.py, doc/man/azurectl::compute::image.md, test/unit/compute_image_task_test.py, test/unit/defaults_test.py, test/unit/image_test.py
Allow to update OS image metadata
=> Added azurectl compute image update

package/spec-template
=> Add missing dependency

azurectl/azurectl_exceptions.py, azurectl/compute_image_task.py, azurectl/image.py, azurectl/version.py, doc/man/azurectl::compute::image.md, test/unit/account_setup_test.py, test/unit/cli_test.py, test/unit/compute_image_task_test.py, test/unit/filetype_test.py, test/unit/image_test.py, test/unit/logger_test.py
... because I'm tired of grep'ing the results.
=> Add command for listing a single image, by name.

azurectl/defaults.py, azurectl/version.py
A few things that needed to be added for complete support of disconnected regions*.
* Mooncake and Black Forest; I don't have access to Fairfax.
=> More disconnected regions

azurectl/version.py, setup.cfg
=> Add bumpversion config

.gitignore, .virtualenv.dev-requirements.txt, .virtualenv.requirements.txt, setup.py
* Add requirement files for development and normal
* Add comment in setup.py's install_requires key (`~=` notation works only for newer pip/setuptools)
=> Prepare virtual environment for Python

.git-hooks/pre-commit, .virtualenv.dev-requirements.txt, Makefile, README.md
A few things that got missed in the switch to virtualenv:
* Added some more dependencies to the README
* Updated the git commit hook to use `flake8`
=> More setup

azurectl/azurectl_exceptions.py, azurectl/compute_endpoint_task.py, azurectl/endpoint.py, doc/man/azurectl::compute::endpoint.md, test/unit/compute_endpoint_task_test.py, test/unit/endpoint_test.py
=> Add commands for managing VM endpoints

azurectl/azurectl_exceptions.py, azurectl/compute_image_task.py, azurectl/image.py, test/unit/compute_image_task_test.py, test/unit/image_test.py
Resolves https://github.com/SUSE/azurectl/issues/89
=> Add commands and arguments for monitoring replication status when publishing images

azurectl/commands/compute_data-disk.py, azurectl/commands/compute_endpoint.py, azurectl/commands/compute_image.py, azurectl/commands/compute_request.py, azurectl/commands/compute_reserved-ip.py, azurectl/commands/compute_vm.py, azurectl/commands/setup_account.py, azurectl/commands/storage_account.py, azurectl/commands/storage_container.py, azurectl/commands/storage_disk.py, azurectl/commands/storage_share.py, doc/man/azurectl::storage::container.md
... branched from https://github.com/SUSE/azurectl/pull/129
=> Doc fixes add sas command

azurectl/commands/compute_data-disk.py, azurectl/commands/compute_endpoint.py, azurectl/commands/compute_image.py, azurectl/commands/compute_request.py, azurectl/commands/compute_reserved-ip.py, azurectl/commands/compute_vm.py, azurectl/commands/setup_account.py, azurectl/commands/storage_account.py, azurectl/commands/storage_container.py, azurectl/commands/storage_disk.py, azurectl/commands/storage_share.py, doc/man/azurectl::compute::image.md, doc/man/azurectl::storage::disk.md, test/unit/commands_compute_image_test.py, test/unit/commands_storage_disk_test.py
=> Doc fixes unify blob name

README.md, azurectl/commands/compute_data-disk.py, azurectl/commands/compute_endpoint.py, azurectl/commands/compute_image.py, azurectl/commands/compute_reserved-ip.py, azurectl/commands/compute_vm.py, azurectl/commands/setup_account.py, azurectl/commands/storage_account.py, azurectl/commands/storage_container.py, azurectl/commands/storage_share.py
... based on the rules we've agreed upon in email+IRC.
=> Doc fixes - reorder subcommands

azurectl/cli.py
=> Provide subcommand help as usage information

azurectl/azurectl.py, azurectl/cli.py
Depending on the selected service different global options
are available. This patch categorizes the global option
information to be specific for the selected service.
Fixes #137
=> Update usage information for global options

azurectl/commands/compute_data-disk.py, azurectl/commands/compute_endpoint.py, azurectl/instance/data_disk.py, azurectl/instance/endpoint.py, test/unit/commands_compute_data-disk_test.py, test/unit/instance_data_disk_test.py, test/unit/instance_endpoint_test.py
```
deployment_name = cloud_service_name
role_name = instance_name
```
=> Fixup role name

azurectl/commands/storage_disk.py, doc/man/azurectl::storage::disk.md
=> 'storage disk delete' uses blob-name argument

azurectl/instance/reserved_ip.py
We don't need storage account information here, Fixes #166
=> Fixed ReservedIp constructor

azurectl/commands/base.py, azurectl/commands/compute_data-disk.py, azurectl/commands/compute_endpoint.py, azurectl/commands/compute_image.py, azurectl/commands/compute_request.py, azurectl/commands/compute_reserved-ip.py, azurectl/commands/compute_vm.py, azurectl/commands/setup_account.py, azurectl/commands/storage_account.py, azurectl/storage/account.py, doc/man/azurectl::compute::data_disk.md, doc/man/azurectl::compute::endpoint.md, doc/man/azurectl::compute::image.md, doc/man/azurectl::compute::reserved_ip.md, doc/man/azurectl::compute::vm.md, doc/man/azurectl::storage::account.md, test/unit/commands_base_test.py, test/unit/commands_compute_data-disk_test.py, test/unit/commands_compute_endpoint_test.py, test/unit/commands_compute_image_test.py, test/unit/commands_compute_request_test.py, test/unit/commands_compute_reserved-ip_test.py, test/unit/commands_compute_vm_test.py, test/unit/commands_setup_account_test.py, test/unit/commands_storage_account_test.py, test/unit/storage_account_test.py
Added --wait for async request, update and fixup the manual pages along with the change
Related to: https://trello.com/c/TDNWTWZW/167-azurectl-next-1
=> Allow wait for request completion in command

azurectl/azurectl_exceptions.py, azurectl/commands/compute_vm.py, azurectl/instance/cloud_service.py, doc/man/azurectl::compute::vm.md, test/unit/commands_compute_vm_test.py, test/unit/instance_cloud_service_test.py
Added compute vm show command
show detailed information about all virtual machines running in the specified cloud service
https://trello.com/c/PDvqeQZN/168-azurectl-next
=> Cloud service information

azurectl/commands/compute_data-disk.py, azurectl/defaults.py, azurectl/instance/data_disk.py, doc/man/azurectl::compute::data_disk.md, test/unit/commands_compute_data-disk_test.py, test/unit/instance_data_disk_test.py
* Refactor DataDisk class
* Update compute data-disk command
=> Data disk detach delete

azurectl/commands/compute_data-disk.py, azurectl/instance/data_disk.py, test/unit/commands_compute_data-disk_test.py, test/unit/instance_data_disk_test.py
Update compute data-disk command
* add data-disk attach subcommand attach an existing data disk to the selected virtual machine
=> Data disk attach

azurectl/azurectl_exceptions.py, azurectl/commands/compute_reserved-ip.py, azurectl/instance/reserved_ip.py, doc/man/azurectl::compute::reserved_ip.md, test/unit/commands_compute_reserved-ip_test.py, test/unit/instance_reserved_ip_test.py
Add support for IP to cloud service associations
```
azurectl compute reserved-ip associate --name my_ip --cloud-service-name my_service
azurectl compute reserved-ip disassociate --name my_ip --cloud-service-name my_service
```
=> Reserved ip association

azurectl/commands/compute_data-disk.py, doc/man/azurectl::compute::data_disk.md
Update data-disk manual page
The man page for this command was not in line with the current state of the command and its subcommands.
=> Data disk doc update

azurectl/instance/data_disk.py, test/unit/instance_data_disk_test.py
=> Adjust data-disk size for vhd footer

azurectl/azurectl_exceptions.py, azurectl/commands/compute_vm.py, azurectl/instance/virtual_machine.py, doc/man/azurectl::compute::vm.md, test/unit/commands_compute_vm_test.py, test/unit/instance_virtual_machine_test.py
Allows to shut down a virtual machine instance. Also taking
into account if the used resources should be deallocated or
not. This Fixes #200
=> Added compute vm shutdown command

azurectl/azurectl_exceptions.py, azurectl/commands/base.py, azurectl/commands/compute_data-disk.py, azurectl/instance/data_disk.py, azurectl/utils/validations.py, doc/man/azurectl::compute::data_disk.md, test/unit/commands_compute_data-disk_test.py, test/unit/instance_data_disk_test.py, test/unit/utils_validations_test.py
=> Use `compute data-disk attach` for either data-disks or VHD page blobs.

azurectl/commands/compute_vm.py, azurectl/instance/virtual_machine.py, doc/man/azurectl::compute::vm.md, test/unit/commands_compute_vm_test.py, test/unit/instance_virtual_machine_test.py
Allows to retrieve the current status of the virtual machine.
In addition it is possible to wait until the machine is in
Running state
=> Added azurectl compute vm status

azurectl/app.py, azurectl/azurectl.py, azurectl/cli.py, azurectl/commands/compute_data-disk.py, azurectl/commands/compute_endpoint.py, azurectl/commands/compute_image.py, azurectl/commands/compute_request.py, azurectl/commands/compute_reserved-ip.py, azurectl/commands/compute_shell.py, azurectl/commands/compute_vm.py, azurectl/commands/setup_account.py, azurectl/commands/storage_account.py, azurectl/commands/storage_container.py, azurectl/commands/storage_disk.py, azurectl/commands/storage_share.py, azurectl/help.py
Update all explicit relative imports to absolute imports.
=> Make all imports absolute.

README.md
... and add an additional note about preselecting the proper subscription.
=> Update path to publishsettings downloader

.gitignore, .virtualenv.dev-requirements.txt, azurectl/azurectl.py, azurectl/cli.py, setup.cfg, tox.ini
In addition the tox setup for easier development has been added
=> Exit code on help and version should be zero
