SUSE/azurectl

- azure_cli/azure_account.py
- azure_cli/azurectl_exceptions.py
- test/data/config.invalid_publishsettings_cert
- test/data/config.invalid_publishsettings_subscription
- test/data/publishsettings.missing_subscription
- test/data/publishsettings_invalid_cert
- test/unit/azure_account_test.py
Exceptions for invalid XML and/or missing Subscription section
are captured as well es decoding errors from pkcs12/base64
decryption
> Handle error conditions for publishsettings import

- .travis.yml
We don't need to `sudo` anything, so lets get off the overloaded VM service and use the shiny new container service.
> Change travis config to allow use of container service

- azure_cli/compute_storage_task.py
- azure_cli/filetype.py
- azure_cli/storage.py
- azure_cli/xz.py
- doc/man/Makefile
- doc/man/azurectl::compute::storage.md
- test/unit/filetype_test.py
- test/unit/storage_test.py
The azurectl compute storage upload command will now detect the
filetype and apply the decompression only for detected types.
If no supported decompressor type is found the file is uploaded
as it is
> Added file type identification for upload source

- azurectl/image.py
- test/unit/image_test.py
The status can be queried with a request ID from the
ServiceManagementService and not from AsynchronousOperationResult
This Fixes #22
> get_operation_status called on the wrong object

- .travis.yml
- azurectl/container.py
- test/unit/container_test.py
The way how shared access signatures are created has changed incompatible
> Fixed azurectl for use with latest SDK version

- azurectl/azurectl_exceptions.py
- azurectl/cloud_service.py
- azurectl/compute_vm_task.py
- azurectl/request_result.py
- test/unit/cloud_service_test.py
- test/unit/compute_vm_task_test.py
- test/unit/request_result_test.py
Encapsulate operations based on a request ID returned from the
Azure API. This makes the code more explicit as well as allows
to think of commands like
azurectl compute request status --id <id>
azurectl compute request wait --id <id>
in the future
> Added RequestResult class

- azurectl/version.py
In accordance with [semantic versioning](http://semver.org/), both the `azure files` functions
and the `compute vm` functions should have been accompanied by a version
bump.
Time to catch up.
> Minor version bump.

- azurectl/logger.py
- test/unit/logger_test.py
The scheduler was still triggering events during upload, causing lots of
log noise around the progress bar.  Proposed solution is to add another
class of event for logging to ignore.
TODO: subversion bump on merge.
> Remove logging noise during uploads.

- .travis.script
- .travis.yml
- azurectl/cloud_service.py
- azurectl/container.py
- azurectl/fileshare.py
- azurectl/image.py
- azurectl/storage.py
- azurectl/virtual_machine.py
- test/unit/cloud_service_test.py
- test/unit/fileshare_test.py
Microsoft will release the dev branch to be the new SDK in August. The version will be at 0.20.x and is incompatible to 0.11.x I have ported the files api support to the dev branch and also updated azurectl to work with the latest dev branch
> Update code base to use SDK's dev branch

- .travis.script
The Azure Storage part of the SDK has been moved into its own
git repository. This testing and also packaging of the SDK
has changed
> Update travis tests due to Azure SDK restructuring

- azurectl/account_setup.py
- azurectl/azure_account.py
- azurectl/setup_account_task.py
- doc/man/azurectl::setup::account.md
- test/data/config.multiple_subscriptions_no_id
- test/data/config.multiple_subscriptions_set_id
- test/data/publishsettings
- test/data/publishsettings.missing_subscription
- test/data/publishsettings.multiple_subscriptions
- test/data/publishsettings_invalid_cert
- test/unit/account_setup_test.py
- test/unit/azure_account_test.py
- test/unit/setup_account_task_test.py
In the event an Azure account holder has more than one subscription, the publishsettings file will have many `<subscription>` tags. 
Its perfectly acceptable (and quite convenient) to leave the subscription id out if only one subscription is in use, but in the case of multiple subscriptions, there needs to be some mechanism for selecting the appropriate subscription.
> Handle accounts with more than one subscription

- README.md
- azurectl/account_setup.py
- azurectl/app.py
- azurectl/azure_account.py
- azurectl/cli.py
- azurectl/cli_task.py
- azurectl/compute_image_task.py
- azurectl/compute_storage_task.py
- azurectl/compute_vm_task.py
- azurectl/config.py
- azurectl/logger.py
- azurectl/setup_account_task.py
- azurectl/version.py
- doc/man/azurectl.md
- doc/man/azurectl::setup::account.md
- test/unit/azure_account_test.py
- test/unit/cli_task_test.py
- test/unit/cli_test.py
- test/unit/cloud_service_test.py
- test/unit/config_test.py
- test/unit/image_test.py
- test/unit/virtual_machine_test.py
With respect to the XDG Base Directory Specification the default
config file location for azurectl has changed. The default config
file is now searched in the following order and paths
1. ~/.config/azurectl/config
2. ~/.azurectl/config
This fixes issue #41
> Moved primary default config file location

- azurectl/account_setup.py
- azurectl/azurectl_exceptions.py
- azurectl/config.py
- azurectl/setup_account_task.py
- doc/man/azurectl::setup::account.md
- test/data/config.corrupted_p12_cert
- test/data/config.empty_publishsettings
- test/data/config.invalid_publishsettings_cert
- test/data/config.invalid_publishsettings_subscription
- test/data/config.missing_publishsettings
- test/data/config.missing_publishsettings_cert
- test/data/config.missing_publishsettings_id
- test/data/config.missing_set_subscription_id
- test/data/config.multiple_subscriptions_no_id
- test/data/config.multiple_subscriptions_set_id
- test/data/config.no_default
- test/data/config.set_subscription_id_missing_id
- test/unit/account_setup_test.py
- test/unit/azure_account_test.py
- test/unit/cloud_service_test.py
- test/unit/config_test.py
- test/unit/image_test.py
- test/unit/setup_account_task_test.py
- test/unit/virtual_machine_test.py
The DEFAULT section in an INI file is handled special by python's config parser implementation. Therefore this patch refactors the way we use the config file sections. Any section of the config file belongs to an account, the DEFAULT section allows to select one of those accounts as the default account with the default_account keyword.
In addition the  
```
azurectl setup account default --name
```
subcommand to handle the default account was added.
This fixes Issue #51
> Config parser default section handling

- azurectl/cloud_service.py
- test/unit/cloud_service_test.py
> When creating a VM using an ssh key, wait for service to create the key dependency before continuing on.

- .travis.requirements.txt
- azurectl/azurectl_exceptions.py
- azurectl/cloud_service.py
- azurectl/defaults.py
- package/spec-template
- setup.py
- test/unit/cloud_service_test.py
- test/unit/defaults_test.py
A requested cloud service will be registered as public address in Azure If this address is already in use the service comes back with a message that is not clear to the user how to fix the situation. This patch adds a DNS check prior to creating a new cloud service and provides a better error message to the user. This fixes Issue #67
> Added check for cloudservice URL

- azurectl/azurectl_exceptions.py
- azurectl/virtual_machine.py
- test/unit/virtual_machine_test.py
When running an instance of an image the following region constraints must be fulfilled
* storage account region and cloud service region matches
* image exists in cloud service region
This patch adds those checks prior to running an instance and provides useful error messages to the user. This fixes Issue #69 and Issue #68
> Added check for region consistency

- azurectl/image.py
- test/unit/image_test.py
My patches to the Azure SDK were accepted, however I had to rename the methods and the class where they live after review by $MS. Thus these changes have an effect on azurectl too
> Adaptions to replication/publishing SDK patches

- azurectl/compute_image_task.py
- azurectl/image.py
- doc/man/azurectl::compute::image.md
- test/unit/image_test.py
The option --regions supports the value 'all', this Fixes #77
> Added support for replicating to all regions

- azurectl/image.py
- test/unit/image_test.py
After an update of e.g privacy_uri the API might have changed the value to be still correct but different from the original value provided on the commandline by e.g a slash (/). Fixes #86
> Fixed check for URI based OS image attributes

- azurectl/azurectl_exceptions.py
- azurectl/page_blob.py
- azurectl/storage.py
- azurectl/version.py
- test/unit/page_blob_test.py
- test/unit/storage_test.py
- test/unit/xz_test.py
Uploading a 30GB image, in 4MB chunks, can be fragile. Instead of giving up and raising an exception the first time a block fails, retry a few times.
re: Issue #91
> Don't die so easily when uploading

- azurectl/azure_account.py
- azurectl/azurectl_exceptions.py
- azurectl/cloud_service.py
- azurectl/constants.py
- azurectl/container.py
- azurectl/image.py
- azurectl/storage.py
- azurectl/version.py
- azurectl/virtual_machine.py
- test/data/config.missing_mgmt_url
- test/data/publishsettings.missing_mgmt_url
- test/unit/azure_account_test.py
- test/unit/cloud_service_test.py
- test/unit/image_test.py
- test/unit/virtual_machine_test.py
Azure has multiple management endpoints, corresponding to disconnected regions. In order to act on services in those disconnected regions, the URLs for management and storage need to be explicitly defined.
> Support disconnected regions

- azurectl/compute_shell_task.py
- test/unit/compute_shell_task_test.py
I find myself hacking this function in over and over, in order to implement new functionality. It makes more sense to just do it once as a command.
> Add `compute shell` command -> drops to interactive python

- azurectl/virtual_machine.py
- test/unit/storage_account_test.py
- test/unit/virtual_machine_test.py
When instantiating a new VM, we create a disk file with the
name '_instance', in the selected storage container. Since
storage files have unique names an additional uniq id information
is required to allow creation of multiple vm's from the same image
in a selected region and container. This fixes #99
> Create a uniq disk identifier on vm create

- azurectl/azurectl_exceptions.py
- azurectl/compute_data_disk_task.py
- azurectl/data_disk.py
- azurectl/defaults.py
- doc/man/azurectl::compute::data_disk.md
- test/unit/compute_data_disk_task_test.py
- test/unit/data_disk_test.py
- test/unit/defaults_test.py
Create empty disks, show and delete individual disks, and list all disks on a VM.
Resolves issue #103
> Commands for managing data disks (non-root/boot disks) on VMs.

- .bumpversion.cfg
- setup.cfg
- setup.py
Seems setup.cfg was overwritten by .bumpversion.cfg accidently.
Restored setup.cfg from commit e0d09e7e019
> Restore .bumpversion.cfg and setup.cfg

- azurectl/compute_storage_task.py
- azurectl/filetype.py
- azurectl/storage.py
- test/unit/filetype_test.py
It's common to use the source filename as the blob filename, and
Storage#upload already handled that behavior, but it didn't account for how
compressed files are handled automatically.
+ Make the argument optional in the command line
+ Properly adjust the filename of compressed files
> Make blobname arg optional on `compute storage upload`

- azurectl/account_setup.py
- azurectl/azurectl_exceptions.py
- azurectl/container.py
- azurectl/data_disk.py
- azurectl/defaults.py
- azurectl/service_manager.py
- azurectl/setup_account_task.py
- azurectl/storage_account.py
- doc/man/azurectl::setup::account.md
- test/unit/account_setup_test.py
- test/unit/container_test.py
- test/unit/setup_account_task_test.py
- test/unit/storage_account_test.py
Allow storage/container creation for account setup
When configuring a new account setup an optional --create parameter exists which will create the provided storage account and the container as part of the azurectl account configuration
References: https://trello.com/c/q09teezP/122-azurectl-better-initial-experience
> Initial experience allow storage account setup on account configuration

- azurectl/commands/compute_image.py
Fixed docopt setup for compute image commands
* Options for the image update command were not part of the usage help
* Be more consistent what --name is used for
* Be more clear and consistent for the --label option
> Compute image usage

- azurectl/azurectl.py
Instead of the docopt way to show the usage information we
provide an azurectl specific usage information. The usage
data now always consists of
* the generic call
```
azurectl [global options] service <command> [<args>]
```
* the command specific usage defined by the docopt string
short form by default, long form with -h | --help
* the global options
> Provide custom usage message

- azurectl/cli.py
- azurectl/commands/compute_vm.py
- azurectl/commands/storage_container.py
- azurectl/config/parser.py
- test/unit/config_parser_test.py
azurectl operations like 'storage account list' or 'compute vm types'
as well as 'compute vm regions' do not require a region setup in the
configuration file. In addition we allow to setup the account with
the region setup to be optional but the code always reads in a default
region setup. Therefore this commit changes the behaviour to read
the region setup only when required and allows for operations without
a region setup. This is related to Issue #124
> Not all operations requires a region setup

- azurectl/commands/storage_container.py
- test/unit/commands_storage_container_test.py
If the container name is optional on create, it is taken from
the region section of the config file. However if the config
file does not contain a region section it is not possible to
create a container. This commit solves the chicken & egg
problem. Related to #124
> Make name argument mandatory for container create

- azurectl/commands/setup_account.py
- test/unit/commands_setup_account_test.py
prior to this release azurectl allowed multiple account
sections in one config file. In order to prevent the
configuration of duplicate and potentially inconsistent
account configurations this patch checks the account
sections of an existing default config file for conflicts
Fixes #138
> Configuration file compatibility

- doc/man/azurectl.md
Commands have moved to 'storage disk' and 'storage container'
commands, which are already documented.
Resolves https://github.com/SUSE/azurectl/issues/149
> Remove deprecated 'compute storage' section from manpage

- azurectl/commands/compute_vm.py
- azurectl/instance/virtual_machine.py
- test/unit/commands_compute_vm_test.py
- test/unit/instance_virtual_machine_test.py
Fixed instance creation if deployment exists
check if the virtual machine deployment already exists. If so any new instance must be created as additional role to the deployment. Only the initial virtual machine instance must be created as a new deployment for the selected cloud service Fixes #144
> Vm instance creation

- azurectl/config/parser.py
- test/unit/config_parser_test.py
There are specific cases where the region argument is valuable
in a function, but not essential to the configuration file.
An example is `storage account create`; it's necessary to define
the region where the storage account will be placed, but a _specific
storage account_ or a _specific container_ is not required (which is
what the config provides); only the name of the region.
In the event the region name is invalid, it will be reflected in an
error raised by the upstream API.
Resolves #152
> Allow a region argument to bypass the config file

- README.md
for clarity
+ We should assume a user is starting from scratch and has no default
region in the configuration at this point
> - Add the --region global option to the account setup command sequence

- Makefile
+ The option will create a tarball that is suitable for local package
builds and does not require a complete functioning development
environment for azurectl. For releases the existing build target should
be used.
> - Add a tar target

- azurectl/instance/cloud_service.py
- azurectl/instance/virtual_machine.py
The constructor requested information which is not always
needed depending on the called instance methods. Therefore
the class requests operational information like container
names, region name, etc only when needed but not directly
at instance creation time. Fixes #158
> Fixup VirtualMachine and CloudService instances

- azurectl/config/parser.py
- test/unit/config_parser_test.py
The information for the storage account and container is connected
to a region section in the configuration file. This means if azurectl
needs to read for example the name of the default storage container
name configured for the default- or commandline provided region,
it has to first read the region section. If the region section
does not exist azurectl provides an error message to the user about
the missing region, however the user requested information about the
storage container and that could confuse users who do not know how
the configuration file is structured. This patch puts together the
complete set of information and forms a more clear error message
for all data read from a region section in the configuration file
> Better error message for storage/container config

- azurectl/config/parser.py
`Config#__get_region_option()` had its own implementation of choosing a region, which conflicted with `Config#get_region_name()`, so we dump it and use `get_region_name()` in both cases.
Resolves https://github.com/SUSE/azurectl/issues/160
> Always parse region name the same way (with the same method)

- azurectl/config/parser.py
If a default account configuration file from a former
azurectl version was found, an error message explaining
the possible options should be displayed
> Better message for default config file conflict

- azurectl/instance/virtual_machine.py
- test/unit/instance_virtual_machine_test.py
Before we start an instance a check is made if the provided image
is reachable by the cloud service. However if the image itself
does not (or not yet) exist azurectl runs into an unhandled
exception
> Fixed OS image lookup in VirtualMachine

- azurectl/azurectl.py
If there are error details from a wrong formatted command line show them at the end of the usage output
> Show error details from docopt if present

- azurectl/azurectl_exceptions.py
- azurectl/commands/compute_vm.py
- azurectl/instance/virtual_machine.py
- doc/man/azurectl::compute::vm.md
- test/data/customdata
- test/unit/commands_compute_vm_test.py
- test/unit/instance_virtual_machine_test.py
re: https://github.com/SUSE/azurectl/issues/177
Also resolves an issue with double-encoding of customdata - the custom
data supplied _should not_ be base64-encoded; this is handled by the
API.
> Handle custom data via file or string on vm creation

- .travis.requirements.txt
- .virtualenv.requirements.txt
- azurectl/commands/compute_data-disk.py
- azurectl/instance/data_disk.py
- doc/man/azurectl::compute::data_disk.md
- package/spec-template
- setup.py
- test/unit/commands_compute_data-disk_test.py
- test/unit/instance_data_disk_test.py
Refactor compute data-disk create command
* allow creation of data disks without a running instance in the background
Example use
```
$ azurectl --account publish compute data-disk create --identifier ms-bob
Created disk: ms-bob-data-disk-2016-08-22T09_15_25.950289
$ azurectl --account publish compute data-disk show \
--disk-name ms-bob-data-disk-2016-08-22T09_15_25.950289
$ azurectl --account publish compute data-disk attach \
--cloud-service-name suse-products --instance-name suma \
--disk-name ms-bob-data-disk-2016-08-22T09_15_25.950289
$ azurectl --account publish compute data-disk detach \
--cloud-service-name suse-products --instance-name suma --lun 0
$ azurectl --account publish compute data-disk delete \
--disk-name ms-bob-data-disk-2016-08-22T09_15_25.950289
```
Operations are in …
> Data disk create

- azurectl/commands/storage_disk.py
I started going down a different path for the blob upload until I skimmed the source and saw that you do in fact skip empty blocks. Nice feature, just thought it'd be good to document it in the man page.
> Document: storage disk upload skips zero'd blocks

- .bumpversion.cfg
- azurectl/commands/compute_image.py
- azurectl/instance/image.py
- azurectl/version.py
- test/unit/commands_compute_image_test.py
- test/unit/instance_image_test.py
This adds the ability to set `show_in_gui` and `recommended_vm_size` for compute images.
This won't work 100% yet because of these bugs:
* https://github.com/Azure/azure-sdk-for-python/issues/793 - recommended_vm_size is not populated
* https://github.com/Azure/azure-sdk-for-python/issues/794 - `show_in_gui` updates do not take effect
But, I can use `--show-in-gui` with a locally patched azure-storage-python package, and the recommended_vm_Size update works... but it will get clobbered on any subsequent updates because of how you've implemented the update logic.
So there's still value in merging this before the python-sdk fixes are implemented/merged.
> add --show-in-gui and --recommended-vm-size to compute image update

- azurectl/instance/data_disk.py
The data disk file must be of the specified size in sparse
containing the vhd metadata at the end of the disk. Azure
only supports fixed size VHD's
> Fixup data disk creation

- azurectl/instance/data_disk.py
- azurectl/storage/storage.py
- test/unit/storage_storage_test.py
The only content in an empty Azure data-disk is the fixed VHD footer, so instead of creating and reading
an arbitary-sized empty file, just upload the footer data.
> Only upload vhd metadata on data-disk create

- azurectl/management/request_result.py
- test/unit/management_request_result_test.py
If the operation status can't be retrieved, try again for
several times before raising an error. Fixes #199
> retry operation status result on failure

- azurectl/commands/base.py
- test/unit/commands_base_test.py
The [get_operation_status](https://github.com/Azure/azure-sdk-for-python/blob/f8dc98625404b75e5d6365ad30c04abc90ee751a/azure-servicemanagement-legacy/azure/servicemanagement/servicemanagementclient.py#L320) command from azure SDK is returning an [Operation](https://github.com/Azure/azure-sdk-for-python/blob/f8dc98625404b75e5d6365ad30c04abc90ee751a/azure-servicemanagement-legacy/azure/servicemanagement/models.py#L747) object not a string.
Return a dictionary with the result status plus the error message if the request has failed.
- I don't think the SDK Operation object should be passed through CliTask.request_status()
- But I do think passing the error message on failure is useful
Hence why I chose to return a dictionary rather than just the status string.
> Return dictionary status from request_status.

- azurectl/instance/virtual_machine.py
- test/unit/instance_virtual_machine_test.py
Each cloud-service created through azurectl has a single deployment which
defines the public network configuration for the cloud-service, including
a reserved-ip if desired.
Each instance (VM) is created with a role, which includes endpoint mapping
for the specific instance from the cloud-service.
A cloud-service with one instance has one deployment, and one role.
A cloud-service with N instances has one deployment, and N roles.
Therefore; deleting the deployment is an incorrect action when a single
instance is targeted for deletion; the instance's role should be deleted
instead.
See https://github.com/Azure/azure-sdk-for-python/blob/master/azure-servicemanagement-legacy/azure/servicemanagement/servicemanagementservice.py#L1599
re: #204
> Delete single instance with delete_role

- azurectl/instance/endpoint.py
- test/unit/instance_endpoint_test.py
Currently the instance endpoint methods all fail if the cloud service and/or instance have no endpoints. Instead of returning an empty list Azure is returning a None type for input_endpoints value.
- Add checks for None
- Add check for endpoint in delete and only delete if it exists
- Create new endpoints list on creation of an endpoint if value is None
> Fix methods if no endpoints exist

- azurectl/azurectl_exceptions.py
- azurectl/commands/compute_endpoint.py
- azurectl/instance/endpoint.py
- doc/man/azurectl::compute::endpoint.md
- test/unit/commands_compute_endpoint_test.py
- test/unit/instance_endpoint_test.py
Add method and cli option to update an existing endpoint on an instance. All args can be changed except the endpoint name. This adds another arg --tcp to allow the choice of tcp, udp or None when updating. If neither option is chosen the current value is maintained.
> Add update method to instance endpoint.

- azurectl/commands/compute_endpoint.py
- azurectl/instance/endpoint.py
- doc/man/azurectl::compute::endpoint.md
- Order should be by CRUD and alpha.
- In delete, show and update compare endpoint names case insensitive.
> Cleanup docs and docstrings.

- azurectl/cli.py
- test/unit/commands_compute_data-disk_test.py
- test/unit/commands_storage_disk_test.py
The argument '--storage-container' was not defined for the top-level storage command, causing an error when using it.
Resolves https://github.com/SUSE/azurectl/issues/215
> Add --storage-container arg to global storage cmd

- azurectl/commands/base.py
- azurectl/utils/validations.py
- test/unit/instance_image_test.py
- test/unit/utils_validations_test.py
- Default values should not contain mutable objects such as lists.
- Default lists are created once at function definition instead of with each call.
> Fix mutable default values.

- azurectl/commands/compute_vm.py
- test/unit/commands_compute_vm_test.py
On reboot no state change can be determined from the API.
Thus we define the safe default and wait for the ReadyRole
even though the vm might already be in that state before
reboot
> Follow up fix for vm wait states
